### ISSUE TITLE
[SUGESTÃO] 🚀 Usar teclas H, J, K e L como alternativas às setas

### ISSUE THREAD

**Issue by NathanFirmo** [cetorres/tn-cli#1]
Eu uso o bastante o terminal e estou acostumado a usar as teclas `H`, `J`, `K` e `L` para navegação, assim como no neovim. O que você acha de implementar algo assim na sua CLI? Infelizmente não consigo ajudar, pois não programo em golang, mas acho que iria deixar o projeto mais legal ainda.

![image](https://user-images.githubusercontent.com/79997705/208952157-49a8d254-669c-44a8-a824-7dc51eb812d5.png)

**Comment by cetorres** [comment]
Ok, vou adicionar esses keybindings. Valeu!
